# Урок 12. Модель Transformer-2
## Задание

Взять датасет
https://huggingface.co/datasets/merionum/ru_paraphraser. Решить задачу парафраза

In [1]:
! pip install -q datasets

     |████████████████████████████████| 431 kB 15.0 MB/s 
     |████████████████████████████████| 115 kB 51.4 MB/s 
     |████████████████████████████████| 212 kB 50.2 MB/s 
     |████████████████████████████████| 120 kB 68.6 MB/s 
     |████████████████████████████████| 127 kB 58.0 MB/s 


In [2]:
!pip install -q transformers

     |████████████████████████████████| 4.9 MB 14.9 MB/s 
     |████████████████████████████████| 6.6 MB 56.6 MB/s 


In [3]:
from datasets import load_dataset

corpus = load_dataset('merionum/ru_paraphraser')

Extracting data files:   0%|          | 0/2 [00:00<?, ?it/s]

0 tables [00:00, ? tables/s]

0 tables [00:00, ? tables/s]

Dataset json downloaded and prepared to /root/.cache/huggingface/datasets/merionum___json/merionum--ru_paraphraser-aad01005423eb70c/0.0.0/e6070c77f18f01a5ad4551a8b7edfba20b8438b7cad4d94e6ad9378022ce4aab. Subsequent calls will reuse this data.


  0%|          | 0/2 [00:00<?, ?it/s]

In [4]:
corpus

DatasetDict({
    train: Dataset({
        features: ['id', 'id_1', 'id_2', 'text_1', 'text_2', 'class'],
        num_rows: 7227
    })
    test: Dataset({
        features: ['id', 'id_1', 'id_2', 'text_1', 'text_2', 'class'],
        num_rows: 1924
    })
})

In [5]:
import pandas as pd

df_train = pd.DataFrame(corpus['train'])
df_train

id   id_1   id_2                                             text_1  \
0         1    201   8159  Полицейским разрешат стрелять на поражение по ...   
1         2    202   8158  Право полицейских на проникновение в жилище ре...   
2         3    273   8167  Президент Египта ввел чрезвычайное положение в...   
3         4    220   8160  Вернувшихся из Сирии россиян волнует вопрос тр...   
4         5    223   8160  В Москву из Сирии вернулись 2 самолета МЧС с р...   
...     ...    ...    ...                                                ...   
7222  25514  34622  34633         Путин освободил от должности ряд генералов   
7223  25524  34566  34654  Облака над Москвой в День Победы разгонят девя...   
7224  25548  34519  34681   Любляна отпразднует День Победы вместе с Москвой   
7225  25549  34565  34681  Девять самолетов ВВС разгонят облака над Москв...   
7226  25577  34584  34722  9 мая метрополитен Петербурга будет работать к...   

                                                 text_2 class  
0     Полиции могут разрешить стрелять по хулиганам ...     0  
1     Правила внесудебного проникновения полицейских...     0  
2     Власти Египта угрожают ввести в стране чрезвыч...     0  
3     Самолеты МЧС вывезут россиян из разрушенной Си...    -1  
4     Самолеты МЧС вывезут россиян из разрушенной Си...     0  
...                                                 ...   ...  
7222  Путин снял с должностей более 20 руководителей...     0  
7223  Путеводитель по Дню Победы: как провести 9 мая...    -1  
7224  В Москве ограничат движение в связи с Днем Победы    -1  
7225  В Москве ограничат движение в связи с Днем Победы    -1  
7226  Мартынов: комендантский час в Донецке 9 мая бу...    -1  

[7227 rows x 6 columns]

In [6]:
df_train['class'].value_counts()

0     2957
-1    2582
1     1688
Name: class, dtype: int64

In [7]:
df_test = pd.DataFrame(corpus['test'])
df_test

id   id_1   id_2                                             text_1  \
0     25349  34420  34421                    Цены на нефть восстанавливаются   
1     25360  34438  34439  "Гоголь-центр" покажет видеозапись скандальног...   
2     25382  34475  34476  Агент: РФС вновь задерживает зарплату Фабио Ка...   
3     25423  34494  34519     День Победы в Москве обещает выдаться облачным   
4     25430  34531  34532  Посол РФ в США: Россия будет бороться с попытк...   
...     ...    ...    ...                                                ...   
1919  28485  37600  37601  Девять человек пострадали при пожаре в жилом д...   
1920  28486  37602  37603  "Химки" победили "Локомотив-Кубань" и сыграют ...   
1921  28499  37606  37618  Полицейские в США застрелили афроамериканца в ...   
1922  28510  37604  37636  Полицейский в США спас мужчину от наводнения, ...   
1923  28562  37594  37698  Почти 30 человек стали жертвами взрыва в мечет...   

                                                 text_2 class  
0     Парламент Словакии поблагодарил народы бывшего...    -1  
1     Кехман запретил «Гоголь-центру» показывать вид...    -1  
2     СМИ: Агент Фабио Капелло грозится подать в суд...    -1  
3      Любляна отпразднует День Победы вместе с Москвой    -1  
4     Правительство запланировало заработать на лоте...    -1  
...                                                 ...   ...  
1919  При пожаре в жилом доме в центре Санкт-Петербу...     1  
1920  "Химки" обыграли "Локомотив-Кубань" и вышли в ...     0  
1921  Полицейский в США спас мужчину от наводнения и...    -1  
1922  Washington Post: В 2015 году полицейские США з...    -1  
1923  Почти десять человек погибли от взрыва на рынк...    -1  

[1924 rows x 6 columns]

In [8]:
from transformers import AutoTokenizer, TFAutoModelForSequenceClassification
import tensorflow as tf

The cache for model files in Transformers v4.22.0 has been updated. Migrating your old cache. This is a one-time only operation. You can interrupt this and resume the migration later on by calling `transformers.utils.move_cache()`.


Moving 0 files to the new cache system


0it [00:00, ?it/s]

Возьмем мультилингвальную бертовую модель для классификации на 3 класса:

In [9]:
tokenizer = AutoTokenizer.from_pretrained("bert-base-multilingual-cased")
model = TFAutoModelForSequenceClassification.from_pretrained("bert-base-multilingual-cased", num_labels=3)

Downloading:   0%|          | 0.00/29.0 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/625 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/996k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/1.96M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/1.08G [00:00<?, ?B/s]

All model checkpoint layers were used when initializing TFBertForSequenceClassification.

Some layers of TFBertForSequenceClassification were not initialized from the model checkpoint at bert-base-multilingual-cased and are newly initialized: ['classifier']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [10]:
model.summary()

Model: "tf_bert_for_sequence_classification"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 bert (TFBertMainLayer)      multiple                  177853440 
                                                                 
 dropout_37 (Dropout)        multiple                  0         
                                                                 
 classifier (Dense)          multiple                  2307      
                                                                 
Total params: 177,855,747
Trainable params: 177,855,747
Non-trainable params: 0
_________________________________________________________________


Токенизируем и создадим тф-датасет:

In [11]:
def tokenize_function(examples):
    return tokenizer(examples["text_1"], examples["text_2"], padding="max_length", truncation=True, return_tensors='tf')

In [12]:
tokenized_datasets = corpus.map(tokenize_function, batched=True)

  0%|          | 0/8 [00:00<?, ?ba/s]

  0%|          | 0/2 [00:00<?, ?ba/s]

In [13]:
full_train_dataset = tokenized_datasets["train"]
full_eval_dataset = tokenized_datasets["test"]

In [14]:
full_train_dataset

Dataset({
    features: ['id', 'id_1', 'id_2', 'text_1', 'text_2', 'class', 'input_ids', 'token_type_ids', 'attention_mask'],
    num_rows: 7227
})

In [15]:
tf_train_dataset = full_train_dataset.remove_columns(['id', 'id_1', 'id_2', 'text_1', 'text_2']).with_format("tensorflow")
tf_eval_dataset = full_eval_dataset.remove_columns(['id', 'id_1', 'id_2', 'text_1', 'text_2']).with_format("tensorflow")

In [16]:
tf_train_dataset['input_ids']

<tf.Tensor: shape=(7227, 512), dtype=int64, numpy=
array([[  101, 45784, 39569, ...,     0,     0,     0],
       [  101,   524, 86310, ...,     0,     0,     0],
       [  101, 60093,   514, ...,     0,     0,     0],
       ...,
       [  101,   520, 10593, ...,     0,     0,     0],
       [  101, 52935, 76669, ...,     0,     0,     0],
       [  101,   130, 14119, ...,     0,     0,     0]])>

In [17]:
num_classes = 3
y_train = tf.keras.utils.to_categorical(tf_train_dataset["class"], num_classes)
y_eval = tf.keras.utils.to_categorical(tf_eval_dataset["class"], num_classes)

In [18]:
y_train

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       ...,
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.]], dtype=float32)

In [19]:
train_features = {x: tf_train_dataset[x] for x in tokenizer.model_input_names}
train_tf_dataset = tf.data.Dataset.from_tensor_slices((train_features, y_train))
train_tf_dataset = train_tf_dataset.shuffle(len(tf_train_dataset)).batch(4)

eval_features = {x: tf_eval_dataset[x] for x in tokenizer.model_input_names}
eval_tf_dataset = tf.data.Dataset.from_tensor_slices((eval_features, y_eval))
eval_tf_dataset = eval_tf_dataset.batch(4)

In [20]:
model.layers

Заморозим для обучения бертовый слой и обучим только выходной плотный слой:

In [21]:
model.layers[0].trainable = False

model.compile(
    optimizer=tf.keras.optimizers.Adam(),
    loss=tf.keras.losses.CategoricalCrossentropy(from_logits=True),
    metrics=[tf.metrics.CategoricalAccuracy('accuracy')],
)

model.summary()

Model: "tf_bert_for_sequence_classification"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 bert (TFBertMainLayer)      multiple                  177853440 
                                                                 
 dropout_37 (Dropout)        multiple                  0         
                                                                 
 classifier (Dense)          multiple                  2307      
                                                                 
Total params: 177,855,747
Trainable params: 2,307
Non-trainable params: 177,853,440
_________________________________________________________________


In [22]:
model.fit(train_tf_dataset, validation_data=eval_tf_dataset, epochs=3)

Epoch 1/3
1807/1807 [==============================] - 484s 253ms/step - loss: 0.9699 - accuracy: 0.5239 - val_loss: 0.9659 - val_accuracy: 0.4886
Epoch 2/3
1807/1807 [==============================] - 450s 249ms/step - loss: 0.8965 - accuracy: 0.5647 - val_loss: 0.9321 - val_accuracy: 0.5852
Epoch 3/3
1807/1807 [==============================] - 449s 249ms/step - loss: 0.8706 - accuracy: 0.5694 - val_loss: 1.0230 - val_accuracy: 0.4761


In [23]:
from tensorflow.keras.callbacks import Callback
from sklearn.metrics import confusion_matrix, f1_score, precision_score, recall_score, classification_report
import numpy as np


class Metrics(Callback):


    def on_test_end(self, epoch, logs=None):
        logits_to_class = {0:0, 1:1, 2:-1}
        val_predict = model.predict(eval_tf_dataset).logits.argmax(axis=1)
        val_predict_lb = np.array([logits_to_class[i] for i in val_predict])
        print('\n', classification_report(df_test['class'].astype('int32'), val_predict_lb))

Посмотрим отчет классификации на тестовом датасете:

In [24]:
model.evaluate(eval_tf_dataset, callbacks=[Metrics()])

481/481 [==============================] - ETA: 0s - loss: 1.0230 - accuracy: 0.4761
               precision    recall  f1-score   support

          -1       0.92      0.15      0.25       772
           0       0.43      0.95      0.60       778
           1       0.69      0.17      0.27       374

    accuracy                           0.48      1924
   macro avg       0.68      0.42      0.37      1924
weighted avg       0.68      0.48      0.39      1924

481/481 [==============================] - 170s 354ms/step - loss: 1.0230 - accuracy: 0.4761


[1.0230026245117188, 0.4760914742946625]

**Вывод:**

Датасет имеет 3 класса: -1 - предложения не идентичны, 1 - предложения полностью идентичны и 0 - предложения почти идентичны. Как видно, модель крайне плохо улавливает такую постановку задачи. Путает между собой полную и неполную идентичность, а также практически не улавливает неидентичность предложений.

Попробуем оставить 2 класса - предложения идентичны или неидентичны. Классы 0 и 1 сольем в один класс:

In [36]:
convert_classes = {'-1': 0, '0': 1, '1': 1}
y_train2 = df_train['class'].map(convert_classes)
y_eval2 = df_test['class'].map(convert_classes)

In [37]:
num_classes = 2
y_train2 = tf.keras.utils.to_categorical(y_train2, num_classes)
y_eval2 = tf.keras.utils.to_categorical(y_eval2, num_classes)

In [38]:
y_train2

array([[0., 1.],
       [0., 1.],
       [0., 1.],
       ...,
       [1., 0.],
       [1., 0.],
       [1., 0.]], dtype=float32)

Возьмем такую же модель для классификации, но с 2-мя классами:

In [39]:
tokenizer = AutoTokenizer.from_pretrained("bert-base-multilingual-cased")
model = TFAutoModelForSequenceClassification.from_pretrained("bert-base-multilingual-cased", num_labels=2)

All model checkpoint layers were used when initializing TFBertForSequenceClassification.

Some layers of TFBertForSequenceClassification were not initialized from the model checkpoint at bert-base-multilingual-cased and are newly initialized: ['classifier']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [40]:
train_features = {x: tf_train_dataset[x] for x in tokenizer.model_input_names}
train_tf_dataset = tf.data.Dataset.from_tensor_slices((train_features, y_train2))
train_tf_dataset = train_tf_dataset.shuffle(len(tf_train_dataset)).batch(64)

eval_features = {x: tf_eval_dataset[x] for x in tokenizer.model_input_names}
eval_tf_dataset = tf.data.Dataset.from_tensor_slices((eval_features, y_eval2))
eval_tf_dataset = eval_tf_dataset.batch(64)

In [41]:
model.layers[0].trainable = False

model.compile(
    optimizer=tf.keras.optimizers.Adam(),
    loss=tf.keras.losses.CategoricalCrossentropy(from_logits=True),
    metrics=[tf.metrics.CategoricalAccuracy('accuracy')],
)

model.summary()

Model: "tf_bert_for_sequence_classification_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 bert (TFBertMainLayer)      multiple                  177853440 
                                                                 
 dropout_113 (Dropout)       multiple                  0         
                                                                 
 classifier (Dense)          multiple                  1538      
                                                                 
Total params: 177,854,978
Trainable params: 1,538
Non-trainable params: 177,853,440
_________________________________________________________________


Также заморозили берт, обучим модель:

In [42]:
model.fit(train_tf_dataset, validation_data=eval_tf_dataset, epochs=3)

Epoch 1/3
113/113 [==============================] - 431s 4s/step - loss: 0.6061 - accuracy: 0.6999 - val_loss: 0.6308 - val_accuracy: 0.6159
Epoch 2/3
113/113 [==============================] - 417s 4s/step - loss: 0.5487 - accuracy: 0.7367 - val_loss: 0.6061 - val_accuracy: 0.6315
Epoch 3/3
113/113 [==============================] - 416s 4s/step - loss: 0.5133 - accuracy: 0.7592 - val_loss: 0.5960 - val_accuracy: 0.7536


In [48]:
model.fit(train_tf_dataset, validation_data=eval_tf_dataset, epochs=1)

113/113 [==============================] - 417s 4s/step - loss: 0.4926 - accuracy: 0.7758 - val_loss: 0.5727 - val_accuracy: 0.6819


In [49]:
model.fit(train_tf_dataset, validation_data=eval_tf_dataset, epochs=1)

113/113 [==============================] - 417s 4s/step - loss: 0.4764 - accuracy: 0.7819 - val_loss: 0.5632 - val_accuracy: 0.6788


In [50]:
model.fit(train_tf_dataset, validation_data=eval_tf_dataset, epochs=1)

113/113 [==============================] - 417s 4s/step - loss: 0.4653 - accuracy: 0.7887 - val_loss: 0.5535 - val_accuracy: 0.7510


In [46]:
class Metrics(Callback):


    def on_test_end(self, epoch, logs=None):
        # logits_to_class = {0:0, 1:1, 2:-1}
        val_predict = model.predict(eval_tf_dataset).logits.argmax(axis=1)
        # val_predict_lb = np.array([logits_to_class[i] for i in val_predict])
        print('\n', classification_report(df_test['class'].map(convert_classes), val_predict))

Посмотрим отчет классификации:

In [51]:
model.evaluate(eval_tf_dataset, callbacks=[Metrics()])

31/31 [==============================] - ETA: 0s - loss: 0.5535 - accuracy: 0.7510
               precision    recall  f1-score   support

           0       0.79      0.52      0.62       772
           1       0.74      0.91      0.81      1152

    accuracy                           0.75      1924
   macro avg       0.76      0.71      0.72      1924
weighted avg       0.76      0.75      0.74      1924

31/31 [==============================] - 157s 5s/step - loss: 0.5535 - accuracy: 0.7510


[0.5535326600074768, 0.7510395050048828]

**Вывод:**

С двумя классами модель справляется лучше. Но по прежнему неидентичность предложений определяется хуже, чем идентичность.